### ISSUE TITLE
License violation detected. Unlicensed module(s) detected

### ISSUE THREAD

**Issue by pastuxso** [yagitoshiro/ImageAsResized#11]
[ERROR] TiVerify: (Timer-0) [534,5920] License violation detected. Unlicensed module(s) detected.  You must be a subscriber to use one or more of the modules included with this project.. Please contact Appcelerator Support.

I need a license to use this module ?, thanks..

**Comment by williamrijksen** [comment]
Same problem here...

**Comment by yagitoshiro** [comment]
change guid.
https://github.com/yagitoshiro/ImageAsResized/blob/master/manifest
