### ISSUE TITLE
Cant add module

### ISSUE THREAD

**Issue by ashconnell** [yagitoshiro/ImageAsResized#2]
What is the correct syntax for entering the module into the tiapp.xml file? eg:

<module version="0.2" platform="android">imageasresized</module>

My error is:

[DEBUG] Detected module for android: org.selfkleptomaniac.ti.imageasresized 0.2 @ C:\Users\Deminetix\AppData\Roaming\Titanium\modules\android\org.selfkleptomaniac.ti.imageasresized\0.2
[DEBUG] Looking for Titanium Module id: imageasresized, version: 0.2, platform: android
[WARN] Couldn't find app module: imageasresized

**Comment by yagitoshiro** [comment]
Class name is "org.selfkleptomaniac.ti.imageasresized" so tieapp.xml should be like this:

``` xml
<modules>
  <module version="0.2">org.selfkleptomaniac.ti.imageasresized</module>
</modules>
```

**Comment by yagitoshiro** [comment]
Now it's 0.4.

``` xml
 <modules>
        <module platform="android" version="0.4">org.selfkleptomaniac.ti.imageasresized</module>
</modules>
```

**Comment by ashconnell** [comment]
..
