### ISSUE TITLE
License issue when using the module

### ISSUE THREAD

**Issue by joscandreu** [yagitoshiro/ImageAsResized#3]
Hello,

I found a problem when trying to compile and use your module.
I had a license issue, telling that I was not allowed to use that module because I was not subscribed.

I solved the issue changing the guid in the manifest.

I presume you are using the same guid for this Open Sourced version and the compiled version in Appcelerator MarketPlace.

Regards,
Jose

**Comment by kosso** [comment]
I had the same issue. 
Try creating a new module on your system, then use the code within this one to make your own. 
That works.

**Comment by joscandreu** [comment]
Thanks. I hope yagitoshiro will change it so it doesn't happen to any other developer.

I also found there are some typos in the examples in readme file.
androimage -> This should be: image_module

**Comment by yagitoshiro** [comment]
Thank you for your report. guid is now updated and pre-compiled binary is added in dist directory so that you can use this module without compilation.

Readme file is updated, too.

**Comment by joscandreu** [comment]
Thanks for your fast response and thanks also for sharing with us this module.
