### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by pong343** [yagitoshiro/ImageAsResized#4]
I can't install it's show
BUILD FAILED
/Users/Mycom/Library/Application Support/Titanium/mobilesdk/osx/3.1.0.GA/module/android/build.xml:163: Compile failed; see the compiler error output for details

**Comment by yagitoshiro** [comment]
double check your ANDROID_NDK path,
update build.properties and try "ant clean && ant".

you can use pre-built binary in dist directory.

**Comment by yagitoshiro** [comment]
I've just updated target sdk to 3.1.0.GA

**Comment by pong343** [comment]
Thanks work for me

**Comment by kosso** [comment]
Btw: I think the latest Titanium SDK 3.1.0.GA has this functionality now built in to it for both iOS and Android.

http://docs.appcelerator.com/titanium/latest/#!/api/Titanium.Blob-method-imageAsResized

**Comment by yagitoshiro** [comment]
You're exactly right, kosso. Try this module if build-in function causes out of memory error.

**Comment by kosso** [comment]
@yagitoshiro Good idea. Thanks. :)

btw: I am looking for someone to build (or help) build a simple iOS module based on the code in a simple sample iOS app I have found. Is this something you could do? If so, contact me :)

**Comment by yagitoshiro** [comment]
@kosso sure. feel free to e-mail me.

**Comment by kosso** [comment]
@yagitoshiro Hi. Did you get my email?

**Comment by yagitoshiro** [comment]
@kosso yep, i'm on leave for a week but i have already downloaded and took a look at it. sorry for keeping you waiting.

**Comment by yagitoshiro** [comment]
I'm so sorry that I'm this late. Please take a look at this repo:
https://github.com/k0sukey/TiCameraView

2013/5/3 Kosso notifications@github.com

**Comment by kosso** [comment]
@yagitoshiro  cool. thanks ;) - I'll post issues over there for that.
