### ISSUE TITLE
Can not resize using "cameraImageAsResized"

### ISSUE THREAD

**Issue by DaikiSuganuma** [yagitoshiro/ImageAsResized#6]
i've tried this code.

``` javascript
var rate = blob.width / 1024;
blob = androimage.cameraImageAsResized(blob, blob.width / rate, blob.height / rate, 0);
```

but this did not work as i expected, it **croped** the image.
the source image is 3264x2448.

this code did not work also.

``` javascript
blob = androimage.cameraImageAsResized(blob, 1024, blob.height * (1024 / blob.width), 0);
```

this code worked fine.

``` javascript
blob = androimage.cameraImageAsResized(blob, blob.width / 2, blob.height / 2, 0);
```

i want to limit the image width.
how do i fix this issue?
ImageAsResized v0.5, Titanium SDK 3.1.1.GA

**Comment by yagitoshiro** [comment]
Due to algorithm, image will be cropped when you change horizontal to vertical ratio of the original image.
This module uses BitmapFactory and BitmapFactory.Options and these Android native bitmap manipulators accept only integer for width and height value.
http://developer.android.com/reference/android/graphics/BitmapFactory.html
http://developer.android.com/reference/android/graphics/BitmapFactory.Options.html

**Comment by DaikiSuganuma** [comment]
thank you for quick reply.
i tried with "parseInt" for the parametar.
but this is not solve my issue.

i will use "imageAsResized" of Titanium native api so far.
this method always crash in android 2.3.3.
that's why i tried to use this module.

anyway, thank you for your help and providing useful module!

**Comment by yagitoshiro** [comment]
I found that reduction ratio must be integer.

``` javascript
//3264x2448
// var rate = blob.width / 1024; // not integer
var rate = 3; // Good! width: 1088; height: 816;
// var rate = 4; // Good! width: 816; height: 612; 

blob = androimage.cameraImageAsResized(blob, blob.width / rate, blob.height / rate, 0);
var imageView = Ti.UI.createImageView({width: 1024; image: blob});
```

**Comment by DaikiSuganuma** [comment]
thank you for your help.
but i want to use under "openPhotoGallery".
user can select own image. this means it can not fix the ratio.

once selected, user upload to server in my app.
upload size is limited 5M in server.
so i want to reduce the image size.

**Comment by yagitoshiro** [comment]
if your main concern is file size, then try this:

``` javascript
  var limit = 1024 * 1024 * 5; // 5MB
  var camera = Ti.Media.openPhotoGallery({
    success: function(e){
      var resized_image = e.media;
      var image_module = require('org.selfkleptomaniac.ti.imageasresized');
      var width = e.cropRect.width;
      var height = e.cropRect.height;
      var length = e.media.length;
      var rate = 2;
      if(length >= limit){
        while(true){
          resized_image = image_module.cameraImageAsResized(resized_image, width / rate, height / rate, 0);
          if(resized_image.length <= limit){
            break;
          }else{rate = rate + 2;}
        }
      }
      // upload resized_image ere
    },
```

**Comment by DaikiSuganuma** [comment]
Great!
I wrote following code, this works fine:

``` javascript
var rate = parseInt(blob.width / 1024);
rate = (rate % 2 == 1) ? rate + 1 : rate;
androimage = require('org.selfkleptomaniac.ti.imageasresized');
alert(blob.width + 'x' + blob.height + ' / ' + rate);
blob = androimage.cameraImageAsResized(blob, blob.width / rate, blob.height / rate, 0);
```

i avoid the loop, because the cameraImageAsResized is heavy task for mobile, right?
and in my case, user can select 1 to 5 photos, then upload to server.

i will try this code in some mobile phone, android 2.3.3.
thank you for your kindness.
